---
region: "eu-west-2"

development_group: "ifbk"

component: "website"
deployment_identifier: "%{deployment_group}-%{deployment_type}-%{deployment_label}"

storage_bucket_name: "%{hiera('development_group')}-%{hiera('component')}-%{hiera('deployment_identifier')}-storage"
website_bucket_name: "%{hiera('development_group')}-%{hiera('component')}-%{hiera('deployment_identifier')}-content"

content_work_directory: "build/content"

admin_role_name: "cross-account-admin-role"
atmc_parent_account_id: "879281328474"
atmc_parent_account_admin_role: "arn:aws:iam::%{hiera('atmc_parent_account_id')}:role/%{hiera('admin_role_name')}"

non_standard_mime_types:
  font/woff2:
    - woff2
  application/manifest+json:
    - webmanifest

max_ages:
  image/jpeg: 300
  image/png: 300
  image/gif: 300
  image/svg+xml: 300
  text/html: 0
  text/css: 300
  application/javascript: 300
  application/font-woff: 2592000
  font/woff2: 2592000
